name: Build Release Artifacts

on: 
  release: 
    types: [created]

jobs:
  build-and-publish:
    name: Build and Release Artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release information
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install py2exe
      - name: Build gen_erate.exe
        run: python setup.py py2exe -O2 -c -b1 -p xtuml,rsl
      - name: Upload gen_erate.exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/gen_erate.exe
          asset_name: gen_erate.exe
          asset_content_type: application/octet-stream
      - name: Build gen_erate.pyz
        run: python setup.py bundle bundle -o dist/gen_erate.pyz
      - name: Upload gen_erate.pyz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/gen_erate.pyz
          asset_name: gen_erate.pyz
          asset_content_type: application/octet-stream
