name: Build Release Artifacts

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and Release Artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get release information
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller
      - name: Build gen_erate.pyz
        run: |
          python -m pip install --upgrade --target dist .
          python -m zipapp --output gen_erate.pyz --python "/usr/bin/env python3" --main "rsl.gen_erate:main" --compress dist
      - name: Upload gen_erate.pyz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: gen_erate.pyz
          asset_name: gen_erate.pyz
          asset_content_type: application/octet-stream
      - name: Build gen_erate.exe
        run: pyinstaller gen_erate.spec
      - name: Upload gen_erate.exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/gen_erate.exe
          asset_name: gen_erate.exe
          asset_content_type: application/octet-stream
